version: '3.4'

services:

    mysql:
        image: mysql
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: 
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_general_ci'